apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  labels:
    env: "base"
  name: cgcom-storage-bucket
  annotations:
    cnrm.cloud.google.com/force-destroy: "true"
spec:
  lifecycleRule:
    - action:
        type: Delete
      condition:
        age: 7
  versioning:
    enabled: true
