apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "false"
  labels:
    env: sharedservices
  name: cluster
spec:
  location: australia-southeast1
  initialNodeCount: 1
  loggingService: logging.googleapis.com/kubernetes
  monitoringService: monitoring.googleapis.com/kubernetes
  networkRef:
    name: sharedservices-network
  subnetworkRef:
    name: sharedservices-subnetwork-0
  masterAuth:
    username: "user"
    password:
      valueFrom:
        secretKeyRef:
          name: sharedservices-containercluster-dep
          key: password
    clientCertificateConfig:
      issueClientCertificate: false
  workloadIdentityConfig:
    identityNamespace: chris-galdes-contino-project.svc.id.goog
